import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { RouterOutputs, api } from "~/utils/api";
const CreatePostWizard = () => {
  const user = useUser();
  if (!user) return null;
  return (
    <div className="flex gap-4 w-full" >
      <img src={user.user?.profileImageUrl} alt="Profile pic" className="w-14 h-14 rounded-full" />
      <input type="text" placeholder="Put Some Emoji!" className="bg-transparent grow outline-none" ></input>
    </div>
  )
}
type PostViewProps = RouterOutputs["posts"]["getAll"][number]
const PostView = (props: PostViewProps) => {
  const { post, author } = props;
  return (
    <div className="flex p-1" >
      <div>
        <img src={author.profileImageUrl} alt="Profile pic" className="w-14 h-14 rounded-full" />
      </div>
      <div key={post.id} className="p-6">
        {post.content}
      </div>
    </div>
  )
}
const Home: NextPage = () => {
  const { data: posts } = api.posts.getAll.useQuery()
  const user = useUser();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="border-slate-200 border-x w-full md:max-w-3xl">
          <div className="border-b-slate-200 border-b p-2">

            {user.isSignedIn ? <CreatePostWizard></CreatePostWizard> : <SignInButton></SignInButton>}
          </div>
          <div className="flex flex-col" >
            {posts?.map((post) => <PostView {...post} key={post.post.id} />)}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
