import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime)
import { type RouterOutputs, api } from "~/utils/api";
import { Loading, LoadingPage } from "~/components/Loading";
import { toast } from "react-hot-toast";
import { useState } from "react";
import Link from "next/link";
const CreatePostWizard = () => {
  const [content, setContent] = useState("")
  const user = useUser();
  const ctx = api.useContext()
  const { mutate: createPost, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: async () => {
      await ctx.posts.getAll.invalidate();
    },
    onError: (e) => {
      const errorMessage = e.data?.zodError?.fieldErrors.content;
      if (errorMessage && errorMessage[0]) {
        toast.error(errorMessage[0]);
      } else {
        toast.error("Failed to post! Please try again later.");
      }
    }

  })
  if (!user) return null;
  const handleInputKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      createPost({ content: content })
      setContent(() => "")
    }
  }
  return (
    <div className="flex gap-4 w-full" >
      <Image src={user.user?.profileImageUrl ?? ""} alt="Profile pic" className="rounded-full" width={56} height={56} />
      <input type="text" placeholder="Put Some Emoji!" value={content} className="bg-transparent grow outline-none" onKeyDown={handleInputKeyPress}
        onChange={(e) => setContent(e.currentTarget.value)} ></input>
      {content != "" && !isPosting && <button onClick={() => { createPost({ content: content }); setContent(() => "") }} >Post</button>}
      {isPosting && <div className="flex justify-center items-center" >
        <Loading size={30}></Loading>
      </div>
      }
    </div>
  )
}
type PostViewProps = RouterOutputs["posts"]["getAll"][number]
const PostView = (props: PostViewProps) => {
  const { post, author } = props;
  return (
    <div className="flex px-1 py-3 gap-4 border border-slate-300" >
      <div>
        <Image src={author.profileImageUrl} alt="Profile pic" className="rounded-full" width={56} height={56} />
      </div>
      <div key={post.id} className="flex flex-col ">
        <div className="flex gap-2">
          <Link href={`/@${author.username ?? ""}`}>
            <div>{`@${author.username ?? ""}`}</div>
          </Link>
          <div>&apos;</div>
          <div>{dayjs(post.createdAt).fromNow()}</div>
        </div>
        <div className="text-2xl">
          <Link href={`/post/${post.id}`}>
            {post.content}
          </Link>
        </div>
      </div>
    </div>
  )
}
const Feed = () => {
  const { data: posts, isLoading: feedIsLoading } = api.posts.getAll.useQuery()
  if (feedIsLoading) return <div className="flex w-full h-screen justify-center items-center " >
    <Loading></Loading>
  </div>
  return (
    <div className="flex flex-col" >
      {posts?.map((post) => <PostView {...post} key={post.post.id} />)}
    </div>
  )
}
const Home: NextPage = () => {
  const { isLoaded, isSignedIn } = useUser();
  // console.log(user);
  if (!isLoaded) return <LoadingPage size={70}></LoadingPage>
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="border-slate-200 border-x w-full md:max-w-3xl">
          <div className="border-b-slate-200 border-b p-2">
            {isSignedIn ? <CreatePostWizard></CreatePostWizard> : <SignInButton></SignInButton>}
          </div>
          <Feed></Feed>
        </div>
      </main>
    </>
  );
};

export default Home;
